# Generated by Django 5.2.5 on 2025-08-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_artist_instagram_artist_tiktok'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='style_images/')),
            ],
        ),
    ]
