# Generated by Django 5.2.5 on 2025-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tattoostyle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('blackgrey', 'Black & Grey'), ('color', 'Color'), ('lettering', 'Lettering'), ('sleeve', 'Sleeve'), ('small', 'Small Tattoos')], max_length=50)),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
