# Generated by Django 5.2.5 on 2025-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(choices=[('fas fa-paint-brush', 'Paint Brush'), ('fas fa-shield-alt', 'Shield'), ('fas fa-hand-sparkles', 'Hand Sparkles'), ('fas fa-brush', 'Brush'), ('fas fa-bolt', 'Bolt'), ('fas fa-spray-can', 'Spray Can')], max_length=50)),
            ],
        ),
    ]
