# Generated by Django 5.2.5 on 2025-08-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('placement', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('reference_images', models.ImageField(blank=True, null=True, upload_to='booking_references/')),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
