# Generated by Django 5.2.5 on 2025-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='preferred_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reference_images',
        ),
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.FileField(blank=True, null=True, upload_to='booking_references/'),
        ),
    ]
