# Generated by Django 5.2.5 on 2025-08-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tattoostyle',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
    ]
