# Generated by Django 5.2.5 on 2025-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_artist_show_on_homepage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='artist',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.FileField(blank=True, null=True, upload_to='references/'),
        ),
    ]
