# Generated by Django 5.2.5 on 2025-08-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_booking_artist_alter_booking_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='booking',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='placement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reference',
            field=models.ImageField(blank=True, null=True, upload_to='booking_references/'),
        ),
    ]
