# Generated by Django 5.2.6 on 2025-09-20 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_rename_created_at_booking_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(600)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='stars',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
