name: Keep Render Awake

on:
  schedule:
    # Run every 5 minutes from 00:15 to 17:45 UTC (which is 6 AM to 11 PM Nepal time)
    - cron: "*/5 0-17 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          curl -I https://tatto-test.onrender.com || true
